### ISSUE TITLE
Return lcp array to module

### ISSUE THREAD

**Issue by fpmenninger** [JuliaCollections/SuffixArrays.jl#13]
The previous version also calculated the lcp array (but did not export it).  Could that be reintroduced and exported?

**Comment by StefanKarpinski** [comment]
If you want to make a PR to bring it back, export it and add some tests, that would be very welcome!

**Comment by StefanKarpinski** [comment]
Btw, I tried using an LCP array (not the adjacency one, but the one specific to doing binary search) to accelerate the substring search here:

https://github.com/JuliaIO/BSDiff.jl/blob/b31defd5f56090c0eda142/src/BSDiff.jl#L295-L320

But it was unhelpful—while it theoretically makes the search faster, it's not actually faster even in cases where there's a lot of strings with the same common prefix. What I ended up doing was just keeping track of the min of the longest common prefix between the high and low indices, which avoids needing and LCP array but allows search to skip whatever is common to the full range of suffixes that the search has been narrowed down to.
